---
title: "Curriculum Vitae"
---

**You can access the full CV [here](https://drive.google.com/file/d/1broikJLCmeh5K4biYXsbPFlgVJVPyhLY/view?usp=drive_link)**

## RECENT PROFESSIONAL EXPERIENCE

-   11/2022–present. Research Fellow, ERC PROJECT "CONSULTATIONEFFECTS": EFFECTS OF STAKEHOLDER CONSULTATIONS ON INPUTS, PROCESSES AND OUTCOMES OF EXECUTIVE POLICYMAKING, Department of Comparative Politics, University of Bergen, Bergen, Norway.

-   11/2020–10/2022. Marie Skłodowska‑Curie Postdoctoral Researcher, HORIZON 2020 PROJECT "PFCORR": DOES PUBLIC FUNDING MATTER? THE EFFECT OF STATE SUBSIDIES TO POLITICAL PARTIES ON POLITICAL CORRUPTION, School of Law and Government, Dublin City University.

## RECENT EDUCATION

-   2014–2019, Ph.D. Political and Social Sciences, European University Institute, Florence, Italy

-   2013–2014, MRes, Political and Social Sciences, European University Institute, Florence, Italy

-   2011–2013, MA, Interdisciplinary Research and Studies on Eastern Europe, University of Bologna, Italy

## RESEARCH GRANTS & FUNDING

-   2023–2027, Pathway Programme Research Fellowship, Dublin City University, School of Law and Government (Amount - €436,035) - Declined

-   2020–2022, Marie Skłodowska-Curie Individual Fellowship, Dublin City University, School of Law and Government (Amount - €184,590) - Completed

-   2016–2017, PhD Research Grant, European University Institute, Department of Political and Social Sciences (Amount - €15,360) - Completed

-   2013–2016, PhD Research Grant, Italian Ministry of Foreign Affairs, managed by the European University Institute (€41,400) - Completed

## SELECTED PRESENTATIONS

-   04-08 September 2023, "Does public funding of political parties affect party systems and electoral competition? Evidence from the post-communist space". ECPR General Conference, Charles University, Prague, Czech Republic.

-   12-14 July 2023, “Understanding patterns of public commenting on bureaucratic policymaking: Evidence from the European Union”, ECPR Biennial Conference of the Standing Group on Regulatory Governance University of Antwerp, Antwerp, Belgium.

-   15-18 September 2022, “Does Public Funding of Parties Reduce Corruption? Evidence from Firm-Level Data”, APSA Annual Meeting, Montréal Convention Centre, Montréal, Canada.

-   23-25 June 2022, “Does state funding of political parties reduce political corruption? Evidence from the post-communist space”, EPSA Annual Conference, Prague Congress Centre, Prague, Czech Republic.

-   03 May 2019, Open Lecture, “Party Finance and Political Corruption in Post-Communist Space”. MA program Interdisciplinary Research and Studies on Eastern Europe, Faculty of Political Sciences Roberto Ruffilli, University of Bologna, Forli, Italy.

-   10 April 2018, “Drawing Electoral Districts Boundaries: Between Neutrality and Political Partisanship”. National Conference, “Towards a functional electoral democracy in Moldova”, Friedrich-Ebert Stiftung & Eastern Partnership Civil Society Forum, Chișinău, Republic of Moldova.

-   15 December 2017, “Problems and Challenges in the Financing of Parliamentary Elections in the Context of the Electoral System Reform”. International Conference, “Financing of Political Parties in the Republic of Moldova: Lessons Learned in the Eastern Partnership”, International IDEA, Konrad-Adenauer-Stiftung, Friedrich-Ebert Stiftung & Central Electoral Committee of the Republic of Moldova, Chișinău, Republic of Moldova.

## RESEARCH SOFTWARE

**Proficient R user**

## LANGUAGE SKILLS

**Romanian (native)**; **Russian (native-level proficiency)**; **English (fluent)**; **Italian (advanced proficiency)**; **French (reading knowledge)**
