---
title: "Publications"
---

## Peer-reviewed articles

Bunea, A., Wüest, R. & Lipcean, S. (2024). Mapping the policy space of public stakeholder consultations: Evidence from the European Union. Journal of European Public Policy. DOI: <https://doi.org/10.1080/13501763.2024.2320836>

Bunea, A. & Lipcean, S. (2023). Understanding patterns of stakeholder participation in public commenting on bureaucratic policymaking: Evidence from the European Union. Regulation & Governance. DOI: <https://onlinelibrary.wiley.com/doi/abs/10.1111/rego.12551>

Lipcean, S. & McMenamin, I. (2023). Rethinking public funding of parties and corruption: Confronting theoretical complexity and challenging measurement. Governance. DOI: <https://doi.org/10.1111/gove.12782>

Lipcean, S. (2022). Direct public funding of political parties: Between proxy measures and hard data. Party Politics 28(6): 1041–1057. DOI: <https://doi.org/10.1177/13540688211037302>

## Book chapters

Lipcean, S. & Casal Bértoa, F. (Forthcoming 2024). Political Financing and Political Corruption. In L. de Sousa & S. Coroado (eds.), Elgar Encyclopedia of Corruption and Society.

Lipcean, S. & Prohnitchi, E. (Forthcoming 2024). Against The Mainstream? The Impact of Party Regulation in Political Competition in Moldova. In F. Casal Bértoa & L. Tsutskiridze (eds.), Money Rules: Parties, Oligarchs and Funding Regulation in Post-Soviet Countries. Routledge, Taylor & Francis Group.

Lipcean, S. & Ștefan, L. (2014). Implementing Right to Information: A Case Study of Moldova. In S. E. Trapnell (ed.), Right to Information: Case Studies on Implementation. Washington, DC: World Bank. [\[link\]](https://openknowledge.worldbank.org/entities/publication/64eb01fb-a69f-5832-81a4-30183fe7ec56)

## Datasets

Lipcean, S. (2021). Dataset on direct public funding of political parties across post-communist regimes 1990-2020. Harvard Dataverse. DOI: <https://doi.org/10.7910/DVN/TNHZML>

## Policy briefs & papers

Lipcean, S., Casal Bértoa, F. & Goguadze, N. (2022). Post-legislative scrutiny of election campaign finance legislation. London: Westminster Foundation for Democracy. [\[link\]](https://www.wfd.org/what-we-do/resources/post-legislative-scrutiny-election-campaign-finance-legislation)

Lipcean, S. & Turcan, R. (2020). Higher Education in Moldova at Crossroads or Throwing Good Money After Bad? Chisinau: Friedrich Ebert Stiftung. [\[link\]](https://moldova.fes.de/fileadmin/user_upload/2020/Publications/Studiu_invatamant_Superior_final_1_EN.pdf)

Berbeca V., Lipcean S. (2020). National Army: Between Group Interests and Strategic Development. Chisinau: Institute of Public Policies. (in Romanian) [\[link\]](https://ipp.md/wp-content/uploads/2020/06/Armata-Nationala-intre-interese-de-grup-si-dezvotare-strategica1.pdf)

Lipcean, S. (2018). Drawing Electoral Districts Boundaries: Between Neutrality and Political Partisanship. Chisinau: Friedrich Ebert Stiftung, IDIS ‘Viitorul’. [\[link\]](https://moldova.fes.de/fileadmin/user_upload/2018/publications/Policy_brief-Gerrymandering-eng.pdf)

Lipcean, S. (2017). Problems and Challenges in the Financing of Parliamentary Elections in the Context of Changing the Electoral System. Chisinau: IDIS ‘Viitorul’, Friedrich Ebert Stiftung. [\[link\]](https://moldova.fes.de/fileadmin/user_upload/2017/publications/Policy_brief-finantare_campanii-ENG.pdf)
